Trigger refactor
VRushLP/RigorMortisGame pull request #116
Opened 2017-01-22 11:52 UTC by tjsg1992

Will bring this up during our Sunday meeting.
The first two commits represent a refactoring of the trigger.js file now that I understand how to do subclassing in Javascript. This I would like to merge for sure.
The third and final commit may be rolled back depending on how you all feel about it. It separates the triggers into individual files. This is mostly personal style, and it's something I'd also like to do to the enemy.js class.

2017-01-22 17:22 UTC, VRushLP approved these changes

2017-01-22 17:22 UTC, VRushLP commented on src/agents/triggers/trigger.js
> +function Trigger(game, x, y, width, height) {
If this kind of Trigger is not intended to actually be used directly, it would be a good idea to rename it "BaseTrigger" or something similar.

2017-01-22 21:14 UTC, tjsg1992 commented on src/agents/triggers/trigger.js
> +function Trigger(game, x, y, width, height) {
Makes sense. I'll make this change on one of the commit states based on which one we decide to go with.

2017-01-23 01:02 UTC, cresse requested changes

2017-01-23 01:02 UTC, cresse commented on index.html
> +    <script type="text/javascript" src="./src/agents/triggers/trigger.js"></script>
duplicate of line 33

2017-01-23 01:02 UTC, cresse commented on src/agents/triggers/trigger.js
> +function Trigger(game, x, y, width, height) {
one of you suggested AbstractTrigger, that's perfect

2017-01-23 05:28 UTC, merged